#############################################################################
#
# Project Makefile
#
# (c) Wouter van Ooijen (www.voti.nl) 2016
#
# This file is in the public domain.
# 
#############################################################################

# source files in this project (main.cpp is automatically assumed)
SOURCES := SI7021.cpp OLED.cpp 

# header files in this project
HEADERS := SI7021.hpp OLED.hpp

# other places to look for files for this project
SEARCH  := 

# TARGET := UART_PORT_UNO
# SERIAL_PORT   ?= COM4

# set RELATIVE to the next higher directory 
# and defer to the appropriate Makefile.* there
RELATIVE := ..
include $(RELATIVE)/Makefile.due
